name: mvvm_architecture_template
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  provider: ^6.0.5

  # language  
  easy_localization: ^3.0.2

  # database - cache
  shared_preferences: ^2.1.2

  # firebase
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2

  # core utilities
  equatable: ^2.0.5

  # ui utilities
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/language/
    - assets/images/